INSERT INTO "org_3_7" ("referentiecode", "org", "beschrijving", "duiding") VALUES
('BIva',	'institute',	'AI-modellen, datasets, onderzoekssoftware',	'Immateriële activa uit R&D en onderwijs; activeren o.b.v. IFRS/NL-RJ criteria'),
('BIva',	'commercial',	'AI-modellen en licenties voor klanten',	'Commercieel inzetbare IP/licenties; activeren en afschrijven volgens beleid'),
('BIva',	'spinoff',	'IP, merk en software',	'Doorontwikkeling/valorisatie in deelnemingen'),
('BMva',	'institute',	'Servers, GPU-nodes, lab-apparatuur',	'Infra voor onderzoek en onderwijs; gebruiksduurgericht afschrijven'),
('BMva',	'commercial',	'Productieservers, devops-hardware',	'Operationele infra voor levering aan klanten'),
('BVas',	'spinoff',	'Beleggingsvastgoed',	'Alleen indien vastgoedvehikel; waardering en exploitatie buiten kern-AI'),
('BFva',	'stichting',	'Deelnemingen/leningen aan missie-vehikels',	'Langetermijnsteun aan maatschappelijke projecten'),
('BFva',	'alliance',	'Deelnemingen in spin-offs en intercompany leningen',	'Houdsterfunctie en kapitaalallocatie'),
('BFva',	'spinoff',	'Belangen in sub-deelnemingen',	'Participaties voor schaal/keten'),
('BVrd',	'institute',	'Voorraad cursus-/onderwijsmaterialen',	'Drukwerk, readers, demo-kits'),
('BVrd',	'commercial',	'Voorraad devices/licenties voor levering',	'Kleine hardwarebundels of pre-paid licenties'),
('BPro',	'institute',	'Onderhanden projecten (onderwijs/onderzoek)',	'Contractonderzoek, gesubsidieerde projecten, nog te factureren uren'),
('BPro',	'commercial',	'Onderhanden implementaties',	'Fixed-fee trajecten en integraties'),
('BVor',	'institute',	'Vorderingen onderwijs/subsidies',	'Debiteuren en nog te ontvangen subsidies'),
('BVor',	'commercial',	'Vorderingen klanten',	'Openstaande facturen en termijnen'),
('BVor',	'spinoff',	'Vorderingen intercompany/klanten',	'Ook convertibles/bridge-notes indien kortlopend'),
('BEff',	'stichting',	'Kortlopende effecten voor liquiditeitsbeheer',	'Conservatief beleggingskader t.b.v. continuïteit'),
('BEff',	'alliance',	'Tijdelijk surplus liquiditeit',	'Parkeren van kasoverschotten'),
('BLim',	'stichting',	'Kas/bank',	'Operationele liquiditeit'),
('BLim',	'alliance',	'Kas/bank',	'Coördinatie en doorstroom naar werk-BV’s'),
('BLim',	'institute',	'Kas/bank',	'Projectstromen en collegegelden'),
('BLim',	'commercial',	'Kas/bank',	'Operationele ontvangsten/uitgaven'),
('BLim',	'spinoff',	'Kas/bank',	'Eigen liquiditeitsbeheer'),
('BEiv',	'stichting',	'Eigen vermogen stichting',	'Bestemmingsreserves en fondsen'),
('BEiv',	'alliance',	'Eigen vermogen holding',	'Inbreng kapitaal en ingehouden winsten'),
('BEiv',	'spinoff',	'Eigen vermogen minderheids/majority',	'Cap table spin-off'),
('BEga',	'stichting',	'Egalisatierekening subsidies',	'Toerekening baten/lasten over perioden'),
('BEga',	'institute',	'Egalisatierekening onderwijs',	'Vereffenen van vooruitontvangen gelden'),
('BVrz',	'alliance',	'Voorzieningen (garanties/reorganisatie)',	'Holdingbrede verplichtingen'),
('BVrz',	'institute',	'Voorzieningen projecten',	'Risico’s contractonderzoek/onderwijs'),
('BVrz',	'commercial',	'Voorzieningen klanten/contracten',	'Nazorg/garantie en onerous contracts'),
('BLas',	'alliance',	'Langlopende leningen',	'Groepsfinanciering en bankleningen'),
('BLas',	'commercial',	'Langlopende leningen',	'Investeringen in sales/infra'),
('BSch',	'alliance',	'Kortlopende schulden',	'Crediteuren/belastingen/IC-afrekeningen'),
('BSch',	'institute',	'Kortlopende schulden',	'Projectcrediteuren en te betalen lonen'),
('BSch',	'commercial',	'Kortlopende schulden',	'Leveranciers/BTW/loonheffingen'),
('WOmz',	'institute',	'Netto-omzet onderwijs/onderzoek',	'Collegegelden, cursussen, contractonderzoek'),
('WOmz',	'commercial',	'Netto-omzet commercieel',	'Licenties, implementatie, abonnementen'),
('WRev',	'spinoff',	'Resultaat exploitatie vastgoed',	'Alleen indien vastgoedspin-off'),
('WRvi',	'spinoff',	'Resultaat verkoop vastgoed in ontwikkeling',	'Projectmatige verkoop'),
('WRgr',	'spinoff',	'Gerealiseerd resultaat verkoop portefeuille',	'Disposals vastgoed'),
('WWvv',	'spinoff',	'Waardeveranderingen vastgoedportefeuille',	'Fair value mutaties'),
('WNoa',	'alliance',	'Netto resultaat overige activiteiten',	'Niet-kern houdsteropbrengsten'),
('WNoa',	'institute',	'Netto resultaat overige activiteiten',	'Nevenactiviteiten campus/kennisdeling'),
('WNoa',	'commercial',	'Netto resultaat overige activiteiten',	'Kleine services/overige'),
('WOvb',	'stichting',	'Overige bedrijfsopbrengsten',	'Subsidies/giften/partnerschappen'),
('WOvb',	'institute',	'Overige bedrijfsopbrengsten',	'Projectsubsidies/consortia'),
('WOvt',	'stichting',	'Opbrengst vaste vorderingen/effecten',	'Rente/dividend op langetermijnbeleggingen'),
('WOvt',	'alliance',	'Opbrengst vaste vorderingen/effecten',	'Rente intercompany/deelnemingen'),
('WVhe',	'stichting',	'Vrijval herwaarderingsreserve',	'Vrijgave bij vervreemding'),
('WVhe',	'alliance',	'Vrijval herwaarderingsreserve',	'Vrijgave bij herstructurering'),
('WFbe',	'alliance',	'Financiële baten en lasten',	'Rente, bankkosten, dividendstromen'),
('WFbe',	'commercial',	'Financiële baten en lasten',	'Rente op leningen/lease'),
('WRed',	'alliance',	'Aandeel resultaat deelnemingen',	'Resultaat uit spin-offs'),
('WLbe',	'stichting',	'Ledenbetalingen/voorschotten',	'Donaties/contributies'),
('WLbe',	'alliance',	'Ledenbetalingen/voorschotten',	'Bijdragen van partners in alliantie'),
('WAad',	'alliance',	'Aandeel derden',	'Minderheidsbelang in groep'),
('WAad',	'spinoff',	'Aandeel derden',	'Minderheids/VC-belang in spin-off'),
('WNer',	'stichting',	'Nettoresultaat',	'Resultaat na bestemming'),
('WNer',	'alliance',	'Nettoresultaat',	'Groepsresultaat na eliminaties'),
('WNer',	'institute',	'Nettoresultaat',	'Resultaat leer/onderzoekseenheid'),
('WNer',	'commercial',	'Nettoresultaat',	'Resultaat commerciële BV'),
('WNer',	'spinoff',	'Nettoresultaat',	'Resultaat entiteit'),
('WOok',	'alliance',	'Overige organisatiekosten',	'Holding-overhead, juridische en administratie'),
('WOok',	'institute',	'Overige organisatiekosten',	'Campus/huisvesting/beheer'),
('WOok',	'commercial',	'Overige organisatiekosten',	'Sales support, office'),
('WKol',	'institute',	'Kosten leefbaarheid/impact',	'Wijk-/maatschappelijke AI-initiatieven'),
('WVkf',	'commercial',	'Verkoopkosten',	'Marketing, acquisitie, partnerfees'),
('WAkf',	'alliance',	'Algemene beheerskosten',	'Management, governance, audit'),
('WWiv',	'commercial',	'Wijziging voorraden',	'Mutaties handelsvoorraad/licenties'),
('WKpr',	'institute',	'Kostprijs van de omzet',	'Docenturen, compute, licentiekosten'),
('WKpr',	'commercial',	'Kostprijs van de omzet',	'Cloud/compute, support, royalties'),
('WPer',	'stichting',	'Personeelslasten',	'Bestuur en projectmatige inzet'),
('WPer',	'alliance',	'Personeelslasten',	'Holding/MT'),
('WPer',	'institute',	'Personeelslasten',	'Docenten/onderzoekers/staf'),
('WPer',	'commercial',	'Personeelslasten',	'Sales/consultants/engineering'),
('WPer',	'spinoff',	'Personeelslasten',	'Kernteam spin-off'),
('WAfs',	'stichting',	'Afschrijvingen IVA/MVA',	'Activa in beheer bij stichting'),
('WAfs',	'alliance',	'Afschrijvingen IVA/MVA',	'Holding-activa'),
('WAfs',	'institute',	'Afschrijvingen IVA/MVA',	'Modellen/hardware R&D'),
('WAfs',	'commercial',	'Afschrijvingen IVA/MVA',	'Productie-infra'),
('WWvi',	'alliance',	'Waardeveranderingen IVA/MVA/vastgoed',	'Impairments/herwaarderingen op groepsactiva'),
('WWvi',	'commercial',	'Waardeveranderingen IVA/MVA/vastgoed',	'Impairments/herwaarderingen op operationele activa'),
('WBwv',	'alliance',	'Overige waardeveranderingen',	'Bijzondere posten/one-offs'),
('WBwv',	'commercial',	'Overige waardeveranderingen',	'Incidentele correcties'),
('WBed',	'stichting',	'Overige bedrijfskosten',	'Diverse niet-gespecificeerde lasten'),
('WBed',	'alliance',	'Overige bedrijfskosten',	'Diverse niet-gespecificeerde lasten'),
('WBed',	'institute',	'Overige bedrijfskosten',	'Diverse niet-gespecificeerde lasten'),
('WBed',	'commercial',	'Overige bedrijfskosten',	'Diverse niet-gespecificeerde lasten'),
('WBel',	'alliance',	'Belastingen',	'VPB/loonheffingen holding'),
('WBel',	'institute',	'Belastingen',	'VPB/loonheffingen onderwijs/onderzoek'),
('WBel',	'commercial',	'Belastingen',	'VPB/loonheffingen commercieel');
-- 2025-09-26 21:33:22 UTC

