INSERT INTO "org_3_7" ("referentiecode", "org", "beschrijving", "duiding") VALUES
('BIva',	'institute',	'AI-modellen, datasets, onderzoekssoftware',	'Immateriële activa uit R&D en onderwijs; activeren o.b.v. IFRS/NL-RJ criteria'),
('BIva',	'commercial',	'AI-modellen en licenties voor klanten',	'Commercieel inzetbare IP/licenties; activeren en afschrijven volgens beleid'),
('BIva',	'spinoff',	'IP, merk en software',	'Doorontwikkeling/valorisatie in deelnemingen'),
('BMva',	'institute',	'Servers, GPU-nodes, lab-apparatuur',	'Infra voor onderzoek en onderwijs; gebruiksduurgericht afschrijven'),
('BMva',	'commercial',	'Productieservers, devops-hardware',	'Operationele infra voor levering aan klanten'),
('BVas',	'spinoff',	'Beleggingsvastgoed',	'Alleen indien vastgoedvehikel; waardering en exploitatie buiten kern-AI'),
('BFva',	'stichting',	'Deelnemingen/leningen aan missie-vehikels',	'Langetermijnsteun aan maatschappelijke projecten'),
('BFva',	'alliance',	'Deelnemingen in spin-offs en intercompany leningen',	'Houdsterfunctie en kapitaalallocatie'),
('BFva',	'spinoff',	'Belangen in sub-deelnemingen',	'Participaties voor schaal/keten'),
('BVrd',	'institute',	'Voorraad cursus-/onderwijsmaterialen',	'Drukwerk, readers, demo-kits'),
('BVrd',	'commercial',	'Voorraad devices/licenties voor levering',	'Kleine hardwarebundels of pre-paid licenties'),
('BPro',	'institute',	'Onderhanden projecten (onderwijs/onderzoek)',	'Contractonderzoek, gesubsidieerde projecten, nog te factureren uren'),
('BPro',	'commercial',	'Onderhanden implementaties',	'Fixed-fee trajecten en integraties'),
('BVor',	'institute',	'Vorderingen onderwijs/subsidies',	'Debiteuren en nog te ontvangen subsidies'),
('BVor',	'commercial',	'Vorderingen klanten',	'Openstaande facturen en termijnen'),
('BVor',	'spinoff',	'Vorderingen intercompany/klanten',	'Ook convertibles/bridge-notes indien kortlopend'),
('BEff',	'stichting',	'Kortlopende effecten voor liquiditeitsbeheer',	'Conservatief beleggingskader t.b.v. continuïteit'),
('BEff',	'alliance',	'Tijdelijk surplus liquiditeit',	'Parkeren van kasoverschotten'),
('BLim',	'stichting',	'Kas/bank',	'Operationele liquiditeit'),
('BLim',	'alliance',	'Kas/bank',	'Coördinatie en doorstroom naar werk-BV’s'),
('BLim',	'institute',	'Kas/bank',	'Projectstromen en collegegelden'),
('BLim',	'commercial',	'Kas/bank',	'Operationele ontvangsten/uitgaven'),
('BLim',	'spinoff',	'Kas/bank',	'Eigen liquiditeitsbeheer'),
('BEiv',	'stichting',	'Eigen vermogen stichting',	'Bestemmingsreserves en fondsen'),
('BEiv',	'alliance',	'Eigen vermogen holding',	'Inbreng kapitaal en ingehouden winsten'),
('BEiv',	'spinoff',	'Eigen vermogen minderheids/majority',	'Cap table spin-off'),
('BEga',	'stichting',	'Egalisatierekening subsidies',	'Toerekening baten/lasten over perioden'),
('BEga',	'institute',	'Egalisatierekening onderwijs',	'Vereffenen van vooruitontvangen gelden'),
('BVrz',	'alliance',	'Voorzieningen (garanties/reorganisatie)',	'Holdingbrede verplichtingen'),
('BVrz',	'institute',	'Voorzieningen projecten',	'Risico’s contractonderzoek/onderwijs'),
('BVrz',	'commercial',	'Voorzieningen klanten/contracten',	'Nazorg/garantie en onerous contracts'),
('BLas',	'alliance',	'Langlopende leningen',	'Groepsfinanciering en bankleningen'),
('BLas',	'commercial',	'Langlopende leningen',	'Investeringen in sales/infra'),
('BSch',	'alliance',	'Kortlopende schulden',	'Crediteuren/belastingen/IC-afrekeningen'),
('BSch',	'institute',	'Kortlopende schulden',	'Projectcrediteuren en te betalen lonen'),
('BSch',	'commercial',	'Kortlopende schulden',	'Leveranciers/BTW/loonheffingen'),
('WOmz',	'institute',	'Netto-omzet onderwijs/onderzoek',	'Collegegelden, cursussen, contractonderzoek'),
('WOmz',	'commercial',	'Netto-omzet commercieel',	'Licenties, implementatie, abonnementen'),
('WRev',	'spinoff',	'Resultaat exploitatie vastgoed',	'Alleen indien vastgoedspin-off'),
('WRvi',	'spinoff',	'Resultaat verkoop vastgoed in ontwikkeling',	'Projectmatige verkoop'),
('WRgr',	'spinoff',	'Gerealiseerd resultaat verkoop portefeuille',	'Disposals vastgoed'),
('WWvv',	'spinoff',	'Waardeveranderingen vastgoedportefeuille',	'Fair value mutaties'),
('WNoa',	'alliance',	'Netto resultaat overige activiteiten',	'Niet-kern houdsteropbrengsten'),
('WNoa',	'institute',	'Netto resultaat overige activiteiten',	'Nevenactiviteiten campus/kennisdeling'),
('WNoa',	'commercial',	'Netto resultaat overige activiteiten',	'Kleine services/overige'),
('WOvb',	'stichting',	'Overige bedrijfsopbrengsten',	'Subsidies/giften/partnerschappen'),
('WOvb',	'institute',	'Overige bedrijfsopbrengsten',	'Projectsubsidies/consortia'),
('WOvt',	'stichting',	'Opbrengst vaste vorderingen/effecten',	'Rente/dividend op langetermijnbeleggingen'),
('WOvt',	'alliance',	'Opbrengst vaste vorderingen/effecten',	'Rente intercompany/deelnemingen'),
('WVhe',	'stichting',	'Vrijval herwaarderingsreserve',	'Vrijgave bij vervreemding'),
('WVhe',	'alliance',	'Vrijval herwaarderingsreserve',	'Vrijgave bij herstructurering'),
('WFbe',	'alliance',	'Financiële baten en lasten',	'Rente, bankkosten, dividendstromen'),
('WFbe',	'commercial',	'Financiële baten en lasten',	'Rente op leningen/lease'),
('WRed',	'alliance',	'Aandeel resultaat deelnemingen',	'Resultaat uit spin-offs'),
('WLbe',	'stichting',	'Ledenbetalingen/voorschotten',	'Donaties/contributies'),
('WLbe',	'alliance',	'Ledenbetalingen/voorschotten',	'Bijdragen van partners in alliantie'),
('WAad',	'alliance',	'Aandeel derden',	'Minderheidsbelang in groep'),
('WAad',	'spinoff',	'Aandeel derden',	'Minderheids/VC-belang in spin-off'),
('WNer',	'stichting',	'Nettoresultaat',	'Resultaat na bestemming'),
('WNer',	'alliance',	'Nettoresultaat',	'Groepsresultaat na eliminaties'),
('WNer',	'institute',	'Nettoresultaat',	'Resultaat leer/onderzoekseenheid'),
('WNer',	'commercial',	'Nettoresultaat',	'Resultaat commerciële BV'),
('WNer',	'spinoff',	'Nettoresultaat',	'Resultaat entiteit'),
('WOok',	'alliance',	'Overige organisatiekosten',	'Holding-overhead, juridische en administratie'),
('WOok',	'institute',	'Overige organisatiekosten',	'Campus/huisvesting/beheer'),
('WOok',	'commercial',	'Overige organisatiekosten',	'Sales support, office'),
('WKol',	'institute',	'Kosten leefbaarheid/impact',	'Wijk-/maatschappelijke AI-initiatieven'),
('WVkf',	'commercial',	'Verkoopkosten',	'Marketing, acquisitie, partnerfees'),
('WAkf',	'alliance',	'Algemene beheerskosten',	'Management, governance, audit'),
('WWiv',	'commercial',	'Wijziging voorraden',	'Mutaties handelsvoorraad/licenties'),
('WKpr',	'institute',	'Kostprijs van de omzet',	'Docenturen, compute, licentiekosten'),
('WKpr',	'commercial',	'Kostprijs van de omzet',	'Cloud/compute, support, royalties'),
('WPer',	'stichting',	'Personeelslasten',	'Bestuur en projectmatige inzet'),
('WPer',	'alliance',	'Personeelslasten',	'Holding/MT'),
('WPer',	'institute',	'Personeelslasten',	'Docenten/onderzoekers/staf'),
('WPer',	'commercial',	'Personeelslasten',	'Sales/consultants/engineering'),
('WPer',	'spinoff',	'Personeelslasten',	'Kernteam spin-off'),
('WAfs',	'stichting',	'Afschrijvingen IVA/MVA',	'Activa in beheer bij stichting'),
('WAfs',	'alliance',	'Afschrijvingen IVA/MVA',	'Holding-activa'),
('WAfs',	'institute',	'Afschrijvingen IVA/MVA',	'Modellen/hardware R&D'),
('WAfs',	'commercial',	'Afschrijvingen IVA/MVA',	'Productie-infra'),
('WWvi',	'alliance',	'Waardeveranderingen IVA/MVA/vastgoed',	'Impairments/herwaarderingen op groepsactiva'),
('WWvi',	'commercial',	'Waardeveranderingen IVA/MVA/vastgoed',	'Impairments/herwaarderingen op operationele activa'),
('WBwv',	'alliance',	'Overige waardeveranderingen',	'Bijzondere posten/one-offs'),
('WBwv',	'commercial',	'Overige waardeveranderingen',	'Incidentele correcties'),
('WBed',	'stichting',	'Overige bedrijfskosten',	'Diverse niet-gespecificeerde lasten'),
('WBed',	'alliance',	'Overige bedrijfskosten',	'Diverse niet-gespecificeerde lasten'),
('WBed',	'institute',	'Overige bedrijfskosten',	'Diverse niet-gespecificeerde lasten'),
('WBed',	'commercial',	'Overige bedrijfskosten',	'Diverse niet-gespecificeerde lasten'),

('BIvaKoo',	'institute',	'Geactiveerde ontwikkelkosten',	'Eigen AI en onderwijsontwikkeling die wordt geactiveerd'),
('BIvaKoo',	'commercial',	'Geactiveerde ontwikkelkosten',	'Productontwikkeling met aantoonbaar toekomstig rendement'),
('BIvaCev',	'institute',	'Intellectuele eigendom en licenties',	'Gekochte data software en IP rechten voor onderzoek'),
('BIvaCev',	'commercial',	'Intellectuele eigendom en licenties',	'Commerciele software patenten en modellen voor klanten'),
('BIvaCev',	'spinoff',	'Intellectuele eigendom en merken',	'Spin-off IP merken en software voor exploitatie'),
('BIvaVoi',	'institute',	'Vooruitbetaalde immateriele projecten',	'Betaalde licenties of ontwikkeltrajecten in voorbereiding'),
('BIvaVoi',	'commercial',	'Vooruitbetaalde immateriele projecten',	'Prepaid software of data tot ingebruikname'),
('BMvaMei',	'institute',	'Servers en researchhardware',	'Compute infrastructuur labinstallaties en GPU clusters voor onderwijs en R&D'),
('BMvaMei',	'commercial',	'Productie- en deliveryhardware',	'Hardware voor managed AI platforms en klantdeployments'),
('BMvaBei',	'institute',	'Inventaris en inrichting',	'Werkplekken labs en campusinrichting'),
('BMvaBei',	'commercial',	'Inventaris en tooling',	'Kantoor en teamuitrusting voor delivery en sales'),
('BVasSvi',	'spinoff',	'Vastgoedbeleggingen in exploitatie',	'Beleggingsvastgoed dat wordt verhuurd binnen vastgoedspin-off'),
('BVasVio',	'spinoff',	'Vastgoedbeleggingen in ontwikkeling',	'Projecten in ontwikkeling voor toekomstige exploitatie of verkoop'),
('BFvaDio',	'stichting',	'Deelnemingen in missiepartners',	'Kapitaalinbreng in maatschappelijke initiatieven en fondsen'),
('BFvaDig',	'alliance',	'Deelnemingen in groepsmaatschappijen',	'Waarde van NederAI werkmaatschappijen onder de holding'),
('BFvaVog',	'alliance',	'Langlopende vorderingen op groepsmaatschappijen',	'Intercompany leningen en rekening courant posities'),
('BFvaAnd',	'spinoff',	'Overige deelnemingen',	'Belangen in aanpalende ventures en joint ventures'),
('BVrdGeh',	'institute',	'Voorraad grond- en hulpstoffen',	'Drukwerk kits en demomaterialen voor onderwijsprojecten'),
('BVrdHan',	'commercial',	'Voorraad handelsgoederen',	'Inkoop van devices licentiebundels en demo units voor klanten'),
('BProOnp',	'institute',	'Onderhanden projecten onderwijs en onderzoek',	'Geactiveerde kosten voor gesubsidieerde en contractprojecten'),
('BProOnp',	'commercial',	'Onderhanden klantprojecten',	'Niet gerealiseerde omzet uit vaste prijs implementaties'),
('BVorDeb',	'institute',	'Handelsdebiteuren onderwijs',	'Openstaande facturen onderwijs en onderzoeksdiensten'),
('BVorDeb',	'commercial',	'Handelsdebiteuren commercieel',	'Facturen voor licenties implementatie en abonnementen'),
('BVorDeb',	'spinoff',	'Handels- en intercompany debiteuren',	'Klantdebiteuren en korte termijn vorderingen op groep'),
('BVorVbk',	'institute',	'Vorderingen belastingen en heffingen',	'Terug te vorderen BTW en loonheffingen onderwijsactiviteiten'),
('BVorVbk',	'commercial',	'Vorderingen belastingen',	'Te ontvangen BTW en loonheffingen vanuit commerciele activiteiten'),
('BVorVog',	'spinoff',	'Vorderingen op groepsmaatschappijen',	'Leningen en rekening courant met holding of zusterbedrijven'),
('BVorTsk',	'institute',	'Te vorderen subsidies',	'Toegezegde maar nog te ontvangen subsidiebaten'),
('BVorOva',	'institute',	'Overlopende activa',	'Vooruitbetaalde kosten en nog te factureren posten'),
('BVorOva',	'commercial',	'Overlopende activa',	'Vooruitbetaalde licenties en nog te factureren services'),
('BVorOva',	'spinoff',	'Overlopende activa',	'Rente verzekeringen en fees vooruitbetaald binnen spin-off'),
('BEffObl',	'stichting',	'Kortlopende obligaties',	'Beleggingen in laagrisico obligaties voor liquiditeitsbuffer'),
('BEffObl',	'alliance',	'Kortlopende obligaties',	'Parkeren van overtollige holdingliquiditeit in staats en bedrijfsobligaties'),
('BLimBan',	'stichting',	'Bankrekeningen',	'Operationele betaal en spaarrekeningen'),
('BLimBan',	'alliance',	'Bankrekeningen',	'Groepsbankrekeningen voor treasury en doorstroom'),
('BLimBan',	'institute',	'Bankrekeningen',	'Project en collegegelden op bank'),
('BLimBan',	'commercial',	'Bankrekeningen',	'Operationele bankrekeningen voor sales en delivery'),
('BLimBan',	'spinoff',	'Bankrekeningen',	'Liquiditeit voor spin-off activiteiten'),
('BLimKas',	'institute',	'Kas en kleine kasmiddelen',	'Beperkte contante middelen op campuslocaties'),
('BLimKas',	'commercial',	'Kas en kleine kasmiddelen',	'Kleine kas voor events en demos'),
('BLimKas',	'spinoff',	'Kas en kleine kasmiddelen',	'Petty cash binnen spin-off teams'),
('BEivBef',	'stichting',	'Bestemmingsfondsen',	'Geoormerkte fondsen voor maatschappelijke projecten'),
('BEivGok',	'alliance',	'Aandelenkapitaal',	'Geplaatst kapitaal van NederAI Alliance BV'),
('BEivAgi',	'alliance',	'Agio',	'Kapitaalstorting boven nominale waarde in holding'),
('BEivGok',	'spinoff',	'Aandelenkapitaal',	'Geplaatst kapitaal van de spin-off entiteit'),
('BEgaEga',	'stichting',	'Egalisatierekening subsidies',	'Tijdsevenwichtsreserve voor meerjarige subsidiebaten'),
('BEgaEga',	'institute',	'Egalisatierekening onderwijs',	'Toerekening van vooruit ontvangen college en projectgelden'),
('BVrzOvz',	'alliance',	'Overige voorzieningen',	'Groepsbrede voorzieningen voor garanties en reorganisaties'),
('BVrzOvz',	'institute',	'Projectvoorzieningen',	'Voorzieningen voor risico s in onderzoek en onderwijsprojecten'),
('BVrzOvz',	'commercial',	'Contractvoorzieningen',	'Voorzieningen voor service levels garanties en verlieslatende deals'),
('BLasSag',	'alliance',	'Langlopende schulden aan groep',	'Intercompany funding vanuit of naar werkmaatschappijen'),
('BLasAoe',	'commercial',	'Langlopende bankleningen',	'Bank en investeringsleningen voor schaal en infrastructuur'),
('BSchSag',	'alliance',	'Kortlopende schulden aan groep',	'Rekening courantpositie met werkmaatschappijen'),
('BSchCre',	'institute',	'Crediteuren en handelskredieten',	'Te betalen leveranciers en projectkosten'),
('BSchCre',	'commercial',	'Crediteuren en handelskredieten',	'Te betalen leveranciers en partners'),
('BSchBep',	'institute',	'Belastingen en sociale lasten kortlopend',	'Te betalen loonheffing en sociale lasten'),
('BSchBep',	'commercial',	'Belastingen en sociale lasten kortlopend',	'Te betalen lonen BTW en sociale lasten'),
('WOmzNod',	'institute',	'Opbrengsten uit diensten',	'Onderwijs onderzoeks en adviesdiensten'),
('WOmzNod',	'commercial',	'Opbrengsten uit diensten',	'Consultancy managed AI en abonnementsinkomsten'),
('WOmzNoh',	'commercial',	'Omzet handelsgoederen',	'Doorverkoop van devices en licentiebundels'),
('WRevHuo',	'spinoff',	'Huuropbrengsten vastgoed',	'Huurinkomsten uit vastgoedexploitatie'),
('WRevLvb',	'spinoff',	'Lasten verhuur en beheer',	'Operationele lasten op vastgoedportefeuille'),
('WRviOvo',	'spinoff',	'Omzet vastgoed in ontwikkeling',	'Verkoopopbrengsten van projecten in ontwikkeling'),
('WRviUvv',	'spinoff',	'Uitgaven vastgoed in ontwikkeling',	'Kosten van bouw en externe partners voor projecten'),
('WRgrOvp',	'spinoff',	'Verkoopopbrengst vastgoedportefeuille',	'Opbrengst bij verkoop van vastgoedbeleggingen'),
('WRgrRvb',	'spinoff',	'Boekwaarde verkochte portefeuille',	'Boekwaarde van afgestoten vastgoed'),
('WWvvNwp',	'spinoff',	'Niet-gerealiseerde waardeveranderingen',	'Fair value mutaties op portefeuille die nog niet gerealiseerd zijn'),
('WNoaOoa',	'alliance',	'Opbrengsten overige activiteiten',	'Nevenopbrengsten zoals kennis en partnerprogramma''s'),
('WNoaOoa',	'institute',	'Opbrengsten overige activiteiten',	'Kennisdeling community en campus events'),
('WNoaOoa',	'commercial',	'Opbrengsten overige activiteiten',	'Kleine services en overige vergoedingen'),
('WOvbBue',	'stichting',	'Baten en giften uit fondsenwerving',	'Donaties en bijdragen van partners voor missieprojecten'),
('WOvbOrs',	'stichting',	'Subsidiebaten',	'Subsidiebaten voor maatschappelijke projecten'),
('WOvbOrs',	'institute',	'Subsidiebaten',	'Projectsubsidies voor onderzoek en onderwijs'),
('WOvbOnm',	'alliance',	'Ontvangen managementvergoeding',	'Doorbelasting van holding en governancekosten'),
('WOvtRof',	'stichting',	'Opbrengst vaste vorderingen',	'Rente en dividend op langlopende beleggingen'),
('WOvtRof',	'alliance',	'Opbrengst vaste vorderingen',	'Intercompany rente en opbrengsten uit deelnemingen'),
('WVheVuh',	'stichting',	'Vrijval herwaarderingsreserve',	'Vrijgave bij besteding van herwaardeerde activa'),
('WVheVuh',	'alliance',	'Vrijval herwaarderingsreserve',	'Vrijval bij herstructurering binnen de groep'),
('WFbeRlm',	'alliance',	'Rente- en beleggingsopbrengsten',	'Rente op intercompany leningen en kortlopende beleggingen'),
('WFbeRls',	'alliance',	'Rentelasten en financieringskosten',	'Kosten van leningen en hedges op holdingniveau'),
('WFbeRls',	'commercial',	'Rentelasten en financieringskosten',	'Financieringskosten op bankleningen en leases'),
('WRedAir',	'alliance',	'Aandeel resultaat deelnemingen',	'Resultaten uit NederAI werkmaatschappijen en spin-offs'),
('WLbeLbv',	'stichting',	'Ledenbetalingen en voorschotten',	'Bijdragen van donateurs en partners voor stichting'),
('WLbeLbv',	'alliance',	'Ledenbetalingen en voorschotten',	'Partnerbijdragen binnen de Alliance structuur'),
('WAadRav',	'alliance',	'Resultaat aandeel derden',	'Minderheidsbelangen in groepsmaatschappijen'),
('WAadRav',	'spinoff',	'Resultaat aandeel derden',	'Extern aandeel in spin-off resultaten'),
('WNerNew',	'alliance',	'Nettoresultaat na belasting',	'Resultaat van de holding na eliminaties'),
('WNerNew',	'institute',	'Nettoresultaat na belasting',	'Resultaat van NederAI Institute BV'),
('WNerNew',	'commercial',	'Nettoresultaat na belasting',	'Resultaat van NederAI Commercial BV'),
('WNerNew',	'spinoff',	'Nettoresultaat na belasting',	'Resultaat van de spin-off entiteit'),
('WOokOok',	'alliance',	'Overige organisatiekosten detail',	'Holding overhead zoals governance advies en compliance'),
('WOokOok',	'institute',	'Overige organisatiekosten detail',	'Campusbeheer facilitaire en ondersteunende lasten'),
('WOokOok',	'commercial',	'Overige organisatiekosten detail',	'Sales enablement marketing en corporate support'),
('WKolKol',	'institute',	'Kosten leefbaarheid en impact',	'Wijk en maatschappelijke AI initiatieven met partners'),
('WVkfVkf',	'commercial',	'Verkoopkosten detail',	'Marketing events en partner fees voor commerciele groei'),
('WAkfAkf',	'alliance',	'Algemene beheerskosten detail',	'Groepsmanagement audit en bestuursondersteuning'),
('WWivWgp',	'commercial',	'Wijziging voorraden goederen',	'Mutatie van handels en demovoorraad'),
('WKprKvp',	'institute',	'Personele kostprijs van de omzet',	'Docenten onderzoekers en support direct aan trajecten'),
('WKprInh',	'commercial',	'Inkoopwaarde handelsgoederen',	'Inkoop van devices en licenties voor klanten'),
('WPerLes',	'stichting',	'Lonen en salarissen',	'Beloning bestuur en programmamedewerkers'),
('WPerLes',	'alliance',	'Lonen en salarissen',	'Management en staf van de holding'),
('WPerLes',	'institute',	'Lonen en salarissen',	'Docenten onderzoekers en supportteams'),
('WPerLes',	'commercial',	'Lonen en salarissen',	'Sales consultants en engineers'),
('WPerLes',	'spinoff',	'Lonen en salarissen',	'Spin-off kernteam en productontwikkeling'),
('WAfsAmv',	'institute',	'Afschrijvingen materiele vaste activa',	'Afschrijvingen op servers labs en inventaris'),
('WAfsAmv',	'commercial',	'Afschrijvingen materiele vaste activa',	'Afschrijvingen op delivery infrastructuur en inventaris'),
('WAfsAiv',	'alliance',	'Afschrijvingen immateriele vaste activa',	'Afschrijvingen op holding brede software en IP'),
('WWviWvm',	'commercial',	'Waardeverminderingen materiele activa',	'Impairments op productie en deliveryhardware'),
('WBwvObw',	'alliance',	'Bijzondere waardeverminderingen vlottend',	'Correcties op kortlopende beleggingen of vorderingen'),
('WBwvObw',	'commercial',	'Bijzondere waardeverminderingen vlottend',	'Afwaarderingen op voorraad debiteuren en derivaten'),
('WBedOvp',	'stichting',	'Overige personeelsgerelateerde kosten',	'Vrijwilligersvergoedingen training en HR faciliteiten'),
('WBedAea',	'alliance',	'Accountants en advieskosten',	'Externe audit juridisch en M&A advies'),
('WBedKan',	'institute',	'Kantoorkosten',	'Huisvesting infrastructuur en campusservices'),
('WBedVkk',	'commercial',	'Verkoop gerelateerde kosten',	'Partners events en customer success kosten'),
('WBelBgr',	'alliance',	'Belastingen bedrijfsresultaat',	'Vennootschapsbelasting en latenties op holdingniveau'),
('WBelBgr',	'institute',	'Belastingen bedrijfsresultaat',	'VPB en latenties op institute niveau'),
('WBelBgr',	'commercial',	'Belastingen bedrijfsresultaat',	'VPB en latenties voor commerciele activiteiten'),
('WBel',	'alliance',	'Belastingen',	'VPB/loonheffingen holding'),
('WBel',	'institute',	'Belastingen',	'VPB/loonheffingen onderwijs/onderzoek'),
('WBel',	'commercial',	'Belastingen',	'VPB/loonheffingen commercieel');
-- 2025-09-26 21:33:22 UTC

